spring:
  application:
    name: swiftlink-api (local)

logging:
  level:
    com.swiftlink: DEBUG
    software.amazon.awssdk: DEBUG

swiftlink:
  base-url: http://localhost:8080
  dynamo-db:
    endpoint: http://localhost:8000
    url-table-name: swiftlink-urls
    analytics-table-name: swiftlink-analytics
